/*
Groq API

API for interacting with Groq's language models and audio transcription/translation services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatMessage{}

// ChatMessage struct for ChatMessage
type ChatMessage struct {
	Role string `json:"role"`
	Content string `json:"content"`
}

type _ChatMessage ChatMessage

// NewChatMessage instantiates a new ChatMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatMessage(role string, content string) *ChatMessage {
	this := ChatMessage{}
	this.Role = role
	this.Content = content
	return &this
}

// NewChatMessageWithDefaults instantiates a new ChatMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatMessageWithDefaults() *ChatMessage {
	this := ChatMessage{}
	return &this
}

// GetRole returns the Role field value
func (o *ChatMessage) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ChatMessage) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ChatMessage) SetRole(v string) {
	o.Role = v
}

// GetContent returns the Content field value
func (o *ChatMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ChatMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ChatMessage) SetContent(v string) {
	o.Content = v
}

func (o ChatMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *ChatMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatMessage := _ChatMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatMessage)

	if err != nil {
		return err
	}

	*o = ChatMessage(varChatMessage)

	return err
}

type NullableChatMessage struct {
	value *ChatMessage
	isSet bool
}

func (v NullableChatMessage) Get() *ChatMessage {
	return v.value
}

func (v *NullableChatMessage) Set(val *ChatMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableChatMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableChatMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatMessage(val *ChatMessage) *NullableChatMessage {
	return &NullableChatMessage{value: val, isSet: true}
}

func (v NullableChatMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


