/*
Groq API

API for interacting with Groq's language models and audio transcription/translation services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ChatCompletionRequestStop - struct for ChatCompletionRequestStop
type ChatCompletionRequestStop struct {
	ArrayOfString *[]string
	String *string
}

// []stringAsChatCompletionRequestStop is a convenience function that returns []string wrapped in ChatCompletionRequestStop
func ArrayOfStringAsChatCompletionRequestStop(v *[]string) ChatCompletionRequestStop {
	return ChatCompletionRequestStop{
		ArrayOfString: v,
	}
}

// stringAsChatCompletionRequestStop is a convenience function that returns string wrapped in ChatCompletionRequestStop
func StringAsChatCompletionRequestStop(v *string) ChatCompletionRequestStop {
	return ChatCompletionRequestStop{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ChatCompletionRequestStop) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			if err = validator.Validate(dst.ArrayOfString); err != nil {
				dst.ArrayOfString = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ChatCompletionRequestStop)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ChatCompletionRequestStop)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ChatCompletionRequestStop) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ChatCompletionRequestStop) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ChatCompletionRequestStop) GetActualInstanceValue() (interface{}) {
	if obj.ArrayOfString != nil {
		return *obj.ArrayOfString
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableChatCompletionRequestStop struct {
	value *ChatCompletionRequestStop
	isSet bool
}

func (v NullableChatCompletionRequestStop) Get() *ChatCompletionRequestStop {
	return v.value
}

func (v *NullableChatCompletionRequestStop) Set(val *ChatCompletionRequestStop) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionRequestStop) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionRequestStop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionRequestStop(val *ChatCompletionRequestStop) *NullableChatCompletionRequestStop {
	return &NullableChatCompletionRequestStop{value: val, isSet: true}
}

func (v NullableChatCompletionRequestStop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionRequestStop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


